In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [24]:
from sklearn.datasets import load_iris
iris_data = load_iris()
df = pd.DataFrame(data=iris_data.data, columns=iris_data.feature_names)

In [27]:
df['Target']=iris_data.target
df=df[df['Target']!=2]

In [28]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Target  
0       0  
1       0  
2       0  
3       0  
4       0

In [29]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [34]:
x

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
1                 4.9               3.0                1.4               0.2
2                 4.7               3.2                1.3               0.2
3                 4.6               3.1                1.5               0.2
4                 5.0               3.6                1.4               0.2
..                ...               ...                ...               ...
95                5.7               3.0                4.2               1.2
96                5.7               2.9                4.2               1.3
97                6.2               2.9                4.3               1.3
98                5.1               2.5                3.0               1.1
99                5.7               2.8                4.1               1.3

[100 rows x 4 columns]

In [35]:
y

0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: Target, Length: 100, dtype: int32

In [30]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=42)

In [31]:
classifier = LogisticRegression()
classifier.fit(x_train,y_train)

LogisticRegression()

In [32]:
y_pred = classifier.predict(x_test)
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1])

In [33]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cm= confusion_matrix(y_test,y_pred=y_pred)
acc= accuracy_score(y_test,y_pred)
print(cm)
print(acc)
print(classification_report(y_test,y_pred))

[[14  0]
 [ 0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        11

    accuracy                           1.00        25
   macro avg       1.00      1.00      1.00        25
weighted avg       1.00      1.00      1.00        25



In [36]:
classifier.predict_proba(x_test)

array([[0.00131876, 0.99868124],
       [0.0168257 , 0.9831743 ],
       [0.00334379, 0.99665621],
       [0.9681417 , 0.0318583 ],
       [0.94085396, 0.05914604],
       [0.97035722, 0.02964278],
       [0.99308972, 0.00691028],
       [0.03341405, 0.96658595],
       [0.97354682, 0.02645318],
       [0.97790287, 0.02209713],
       [0.95381819, 0.04618181],
       [0.95903846, 0.04096154],
       [0.00471857, 0.99528143],
       [0.98517651, 0.01482349],
       [0.00997426, 0.99002574],
       [0.98050496, 0.01949504],
       [0.00231911, 0.99768089],
       [0.001408  , 0.998592  ],
       [0.97334143, 0.02665857],
       [0.95974935, 0.04025065],
       [0.00792767, 0.99207233],
       [0.02306954, 0.97693046],
       [0.95816672, 0.04183328],
       [0.98318739, 0.01681261],
       [0.02809199, 0.97190801]])

In [37]:
classifier.predict_log_proba(x_test)

array([[-6.63106535e+00, -1.31962772e-03],
       [-4.08484781e+00, -1.69688600e-02],
       [-5.70064898e+00, -3.34939767e-03],
       [-3.23768170e-02, -3.44645737e+00],
       [-6.09673454e-02, -2.82774568e+00],
       [-3.00910121e-02, -3.51853653e+00],
       [-6.93426195e-03, -4.97474578e+00],
       [-3.39877893e+00, -3.39850509e-02],
       [-2.68093639e-02, -3.63237879e+00],
       [-2.23449259e-02, -3.81230767e+00],
       [-4.72822071e-02, -3.07516918e+00],
       [-4.18241015e-02, -3.19512168e+00],
       [-5.35625040e+00, -4.72973327e-03],
       [-1.49344591e-02, -4.21154198e+00],
       [-4.60774794e+00, -1.00243318e-02],
       [-1.96875709e-02, -3.93759540e+00],
       [-6.06657354e+00, -2.32179923e-03],
       [-6.56558624e+00, -1.40899045e-03],
       [-2.70203510e-02, -3.62464471e+00],
       [-4.10831208e-02, -3.21262916e+00],
       [-4.83739621e+00, -7.95926026e-03],
       [-3.76924234e+00, -2.33398020e-02],
       [-4.27334883e-02, -3.17406305e+00],
       [-1.